builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
