name: Test CLI
on:
  push:
    branches:
      - '*'
  pull_request:

env:
  GO_VERSION: 1.15

jobs:
  test-local:
    name: Test local sources
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test Go
        run: go test -race ./...
      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1.1.1
        with:
          context: test-${{ matrix.os }}
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
      - name: Set Check Status Failure
        if: failure() || cancelled()
        uses: Sibz/github-status-action@v1.1.1
        with:
          context: test-${{ matrix.os }}
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: failure

  test-public:
    name: Test publishing coverage and release
    runs-on: ubuntu-latest
    needs: test-local
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Take Coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: coverage.txt
      - name: Get Semantic Version
        uses: kyoh86/git-vertag-action@v1
        with:
          method: "get"
      - name: Run GoReleaser (dry-run)
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist --skip-publish --snapshot
      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1.1.1
        with:
          context: test-public
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
      - name: Set Check Status Failure
        if: failure() || cancelled()
        uses: Sibz/github-status-action@v1.1.1
        with:
          context: test-public
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: failure
