name: Relase CLI to the GitHub Release
on:
  workflow_dispatch:
    inputs:
      word:
        description: |
          Which number to increment in the semantic versioning.
          Set major, minor, patch or release.
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Bump-up Semantic Version
        id: update-semver
        run: go run github.com/kyoh86/git-vertag --fetch ${{ github.event.inputs.word }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release --rm-dist
