on: ["push"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Bump-up Semantic Version
        id: update-semver
        run: |
          git fetch --tags
          go run github.com/kyoh86/git-vertag
          echo "::set-output name=next-tag::$(git-vertag patch)"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish
