name: Review with golangci-lint

on: [pull_request]

jobs:
  lint:
    name: Review with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-golangci-lint@v1
        with:
          level: info
          github_token: ${{ secrets.GITHUB_TOKEN }}
